### ISSUE TITLE
Line count ends at 29999 and not 30000

### ISSUE THREAD

**Issue by Enscivwy** [kuskoman/FizzBuzz#6]

**Comment by kuskoman** [comment]
@Enscivwy line count is very important- as everyone knows, more lines = better quality of software. However, optimization is also a very important thing. Currently, there is only 9999 numbers to check- adding next one would not only make file length equal to 30002 lines instead of expected 30000, but also slow code execution  by 0,20003% (1.00020003 times more operations to execute).
Also, it would really decerase the readability. I am aiming on producing easy-to-read and easy-to-rewrite-during-junior-job-interview software so adding three, or even one line would make my project totally useless because being too long to be manually rewriten in time which is set by recruiter.
If you are looking for more enterprise-class solutions I highly recommend you visiting https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition repository. 
Feel free to open another issue if my instructions were unclear and for example somebodys duck got stuck in dishwasher.
Thanks for contribution,
manager of nothing, Jakub Surdej
